#%RAML 1.0
title: ReteriveTravelOnTipRouteAndSchedule
description: This RAML file will reterive TravelOnTip Routes and Schedules

uses:
  commonLib: /libraries/common/commonBusiness-library.raml
  getRoutesLib : /libraries/routes/getRoutesBusiness-library.raml
  getSchedulesLib: /libraries/schedules/getSchedulesBusiness-library.raml
 
/booking:
  /{transportType}:
    /{transportCompany}:
      /routes:
        get:
          is:
            - commonLib.trsnsactionId
          responses:
            200:
              body:
                application/json:
                  type: getRoutesLib.getRoutes
                  example: !include /libraries/routes/examples/getRoutes-200-response-example.json
                    
            400:
              body:
                application/json:     
                  type: commonLib.commonError
                  example: !include /libraries/common/examples/400-response-examples.json
            404:
              body:
                application/json:     
                  type: commonLib.commonError
                  example: !include /libraries/common/examples/404-response-examples.json
                    
            500:
              body:
                application/json:     
                  type: commonLib.commonError
                  example: !include /libraries/common/examples/500-response-examples.json
      /schedules:
        get:
          is:
            - commonLib.trsnsactionId
            - commonLib.departureLocation
            - commonLib.destinationLocation
          responses:
            200:
              body:
                application/json:
                  type: getSchedulesLib.getSchedules
                  example: !include /libraries/schedules/examples/getSchedules-200-response-example.json    
            400:
              body:
                application/json:     
                  type: commonLib.commonError
                  example: !include /libraries/common/examples/400-response-examples.json
            404:
              body:
                application/json:     
                  type: commonLib.commonError
                  example: !include /libraries/common/examples/404-response-examples.json
            500:
              body:
                application/json:     
                  type: commonLib.commonError
                  example: !include /libraries/common/examples/500-response-examples.json